In [1]:
from modules.functions import load_training_labels, load_training_batch, data_to_image
from modules.basic_convo import QTransConv, train_model

In [2]:
labels = load_training_labels()

In [3]:
model = train_model(labels)

TypeError: __init__() got an unexpected keyword argument 'profiler_memory'

In [4]:
import numpy as np
import random
np1 = np.zeros((10, ))
np2 = np.zeros((10, ))
np3 = np.zeros((10, ))

def fill(arr):
    for i in range(arr.shape[0]):
        if random.random() < .6:
            arr[i] = random.random()
    return arr

np1 = fill(np1)
np2 = fill(np2)
np3 = fill(np3)

In [5]:
print(np1)
print(np2)
print(np3)

[0.         0.11601637 0.         0.         0.68305533
 0.         0.         0.6868854  0.5832163  0.        ]
[0.         0.74966586 0.         0.         0.88632825
 0.61978832 0.         0.29680572 0.48174126 0.02801845]
[0.53161088 0.         0.38445353 0.         0.73756836
 0.81076474 0.         0.1191773  0.4543285  0.        ]


In [6]:
np1 + np2 + np3

array([0.53161088, 0.86568223, 0.38445353, 0.        ,
       2.30695193, 1.43055305, 0.        , 1.10286843,
       1.51928606, 0.02801845])

In [7]:
np1 - np2 - np3

array([-0.53161088, -0.63364949, -0.38445353,  0.        ,
       -0.94084128, -1.43055305,  0.        ,  0.27090238,
       -0.35285346, -0.02801845])

In [8]:
np1 * np2 * np3

array([0.        , 0.        , 0.        , 0.        ,
       0.44653217, 0.        , 0.        , 0.02429686,
       0.12764784, 0.        ])

In [ ]:
# Playing around with data/checking spectrogram vals and other transformsimport numpy as np
from scipy.signal import spectrogram
import matplotlib.pyplot as plt
import gwpy

In [ ]:
data = np.load("train/0/0/0/00000e74ad.npy")[1]

In [ ]:
tm, freq, spec = spectrogram(data, 2048, nperseg=8, noverlap=2)

In [ ]:
plt.pcolormesh(freq, tm, spec)

In [ ]:
def prepare_signal(signal, low_freq=35, high_freq=400, band = False):
    whitened = signal.whiten(window=("tukey", 0.2)) #This is similar to what happens with window=None in spectrogram
    if band:
        banded = whitened=bandpass(low_freq, high_freq) #I might remove this tbh, dunno if anomalies happen here
        return banded
    return whitened

def q_transform(signal, qlow=16, qhigh=32, freqlow=30, freqhigh=450):
    return signal.q_transform(qrange=(qlow, qhigh), frange=(freqlow, freqhigh), logf=True, whiten=False)

from gwpy.timeseries import TimeSeries

#Important -- signal is loaded as a GWpy TimeSeries, with sample_rate set to the sample hertz, 2048
signal = TimeSeries(data, sample_rate=2048)
signal = prepare_signal(signal)


In [ ]:
qtrans = q_transform(signal)
figure = qtrans.plot(figsize=[25, 15])
ax = figure.gca()
ax.grid(False)


In [ ]:

maxi_x = 0
maxi_y = 0
v = 0
for i in range(qtrans.shape[0]):
    print("i?", i)
    for j in range(qtrans.shape[1]):
        if qtrans[i][j] > v:
            v = qtrans[i][j]
            maxi_x = i
            maxi_y = j
print(maxi_x, maxi_y)

In [ ]:
qtrans[316][438]

In [ ]:
qtrans2 = qtrans.copy()
for i in range(10, 20):
    for j in range(450, 475):
        qtrans2[i][j] = 25
figure2 = qtrans2.plot(figsize=[25, 15])
ax2 = figure2.gca()
ax2.grid(False)

In [ ]:
from modules.functions import load_training_labels

In [ ]:
#Check for no imbalance
counts = {0: 0, 1: 0}
labels= load_training_labels()
for key in labels:
    if labels[key]:
        counts[1] += 1
    else:
        counts[0] += 1
for key in counts:
    print(key, counts[key]/len(labels))

In [ ]:
qtrans.shape

In [ ]:
import torch
tmp = torch.randn(5, 3, 1, 10, 5)

In [ ]:
tmp[0]

In [ ]:
def view_diff(x):
    #print(x)
    x = torch.transpose(x, 2, 3)
    print(x.shape)
    
view_diff(tmp[:, 0, :, :, :])